ProjectTravelSA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('Aplicaciones.ModeloInicio.urls'), name="inicio_urls"),
    path('', include('Aplicaciones.ModuloUsuario.urls'), name="usuarios_urls"),
    path('', include('Aplicaciones.ModuloTickets.urls'), name="tickets_urls"),
]

Aplicaciones/ModuloTickets/models.py
from django.db import models

# Create your models here.

class tickets(models.Model):
     id = models.AutoField(primary_key= True)
     nombre = models.CharField(max_length=22)
     inicio = models.CharField(max_length= 80)
     destino = models.CharField(max_length= 80)
     tarifa = models.BigIntegerField(max_length= 80)
     horario = models.CharField(max_length =80)
     bus = models.CharField(max_length=44)

class Ciudades(models.Model):
    ciudad = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'ciudades'

class Ciudadesd(models.Model):
    ciudad = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'ciudadesd'

class Tarifas(models.Model):
    precios = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'tarifas'


class Horario(models.Model):
    hora_salida = models.CharField(max_length=11)

    class Meta:
        managed = False
        db_table = 'horario'


class ModulousuarioUsuario(models.Model):
    nombre = models.CharField(max_length=80)
    apellido = models.CharField(max_length=80)
    telefono = models.CharField(max_length=80)
    correo = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'modulousuario_usuario'

class Vehiculos(models.Model):
    marca = models.CharField(max_length=20)
    placa = models.CharField(max_length=6)

    class Meta:
        managed = False
        db_table = 'vehiculos'

templates/ticketsHTMLS/formtickets.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="{% static 'imgs/bus.ico' %}" type="image/x-icon">
      <title>tickets</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/edittickets.css' %}">
</head>

<body>
      <form class="form" method="post">
            <h4>tickets</h4>
            <input type="hidden" name="csrfmiddlewaretoken"
                  value="RwfJnVOmWXwhrUhcHEFTrncDhknI4p8OUoxmgZOBeqgYEhqsqyn9aKg6P276HV0W">


                  <tr>
                        <th><label for="id_nombre">Nombre del Usuario:</label></th>
                        <td>
      
                              <select type="text" name="nombre" maxlength="80" required id="id_nombre">
                                    {% for usuario in usuario  %}
                                    <option value="{{usuario.id}}">{{usuario.nombre}}</option>
                                    {% endfor%}
                              </select>
      
      
                        </td>
                  </tr>      
            <tr>
                  <th><label for="id_inicio">Inicio:</label></th>
                  <td>

                        <select type="text" name="inicio" maxlength="80" required id="id_inicio">
                              {% for ciudades in ciudad  %}
                              <option value="{{ciudades.id}}">{{ciudades.ciudad}}</option>
                              {% endfor%}
                        </select>


                  </td>
            </tr>

            <tr>
                  <th><label for="id_destino">Destino:</label></th>
                  <td>

                        <select type="text" name="destino" maxlength="80" required id="id_destino">
                              {% for ciudades in ciudad  %}
                              <option value="{{ciudades.id}}">{{ciudades.ciudad}}</option>
                              {% endfor%}
                        </select>


                  </td>
            </tr>

            <tr>
                  <th><label for="id_tarifa">Tarifa:</label></th>
                  <td>

                        <select type="number" name="tarifa" min="-9223372036854775808" max="9223372036854775807" required
                              id="id_tarifa">
                              {% for tarifas in tarifas  %}
                              <option value="{{tarifas.id}}">{{tarifas.precios}}</option>
                              {% endfor%}
                        </select>
                        


                  </td>
            </tr>

            <tr>
                  <th><label for="id_horario">Horario:</label></th>
                  <td>

                        <select type="text" name="horario" maxlength="80" required id="id_horario">
                              {% for horario in horario  %}
                              <option value="{{horario.id}}">{{horario.hora_salida}}</option>
                              {% endfor%}
                        </select>




                  </td>
            </tr>
            <tr>
                  <th><label for="id_bus">selecciona tu bus:</label></th>
                  <td>

                        <select type="text" name="bus" maxlength="80" required id="id_bus">
                              {% for vehiculos in vehiculo  %}
                              <option value="{{vehiculos.id}}">{{vehiculos.marca}}</option>
                              {% endfor%}
                        </select>
                  </td>
            </tr>
            
           
            <br>
            <button type="submit" class="btn btn-success btn">ingresar</button>
            <br>
            <a href="/tickets" class="btn btn-secondary btn">atras</a>
      </form>
</body>

</html>

templates/ticketsHTMLS/formupdatetickets.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="shortcut icon" href="{% static 'imgs/bus.ico' %}" type="image/x-icon">
      <title>tickets</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/edittickets.css' %}">
</head>

<body>
      <form class="form" method="post">
            <h4>tickets</h4>
            <input type="hidden" name="csrfmiddlewaretoken"
                  value="RwfJnVOmWXwhrUhcHEFTrncDhknI4p8OUoxmgZOBeqgYEhqsqyn9aKg6P276HV0W">
                  <tr>
                        <th><label for="id_nombre">Nombre del Usuario:</label></th>
                        <td>
      
                              <select type="text" name="nombre" maxlength="80" required id="id_nombre">
                                    {% for usuario in usuario  %}
                                    <option value="{{usuario.id}}">{{usuario.nombre}}</option>
                                    {% endfor%}
                              </select>
      
      
                        </td>
                  </tr> 
            
            
                  <tr>
                  <th><label for="id_inicio">cuidad de salida:</label></th>
                  <td>

                        <select type="text" name="inicio" maxlength="80" required id="id_inicio">
                              {% for ciudades in ciudad %}
                              <option value="{{ciudades.id}}">{{ciudades.ciudad}}</option>
                              {% endfor%}
                        </select>


                  </td>
            </tr>

            <tr>
                  <th><label for="id_destino">cuidad de Destino:</label></th>
                  <td>

                        <select type="text" name="destino" maxlength="80" required id="id_destino">
                              {% for ciudades in ciudad %}
                              <option value="{{ciudades.id}}">{{ciudades.ciudad}}</option>
                              {% endfor%}
                        </select>


                  </td>
            </tr>

            <tr>
                  <th><label for="id_tarifa">Tarifa:</label></th>
                  <td>

                  

                        <select type="number" name="tarifa" min="-9223372036854775808" max="9223372036854775807"
                              required id="id_tarifa">
                              {% for tarifas in tarifas %}
                              <option value="{{tarifas.id}}">{{tarifas.precios}}</option>
                              {% endfor%}
                        </select>


                  </td>
            </tr>

            <tr>
                  <th><label for="id_horario">Horario:</label></th>
                  <td>

                        <select type="text" name="horario" maxlength="80" required id="id_horario"
                              value="{{form.horario.value}}">
                              {% for horario in horario  %}
                              <option value="{{horario.id}}">{{horario.hora_salida}}</option>
                              {% endfor%}
                        </select>




                  </td>
            </tr>
            <tr>
                  <th><label for="id_bus">selecciona tu bus:</label></th>
                  <td>

                        <select type="text" name="bus" maxlength="80" required id="id_bus">
                              {% for vehiculos in vehiculo  %}
                              <option value="{{vehiculos.id}}">{{vehiculos.marca}}</option>
                              {% endfor%}
                        </select>
                  </td>
            </tr>
            <br>
            <button type="submit" class="btn btn-success btn">ingresar</button>
            <br>
            <a href="/tickets" class="btn btn-secondary btn">atras</a>
      </form>

      <script>
             function nombre() {
                  document.getElementById('id_nombre').value = '{{form.nombre.value}}';
            }
            function optioncitys() {
                  document.getElementById('id_inicio').value = '{{form.inicio.value}}';
            }
            function optioncitys2() {
                  document.getElementById('id_destino').value = '{{form.destino.value}}';
            }
            function tarifas() {
                  document.getElementById('id_tarifa').value = '{{form.tarifa.value}}';
            }
            function horario() {
                  document.getElementById('id_horario').value = '{{form.horario.value}}';
            }
            function bus() {
                  document.getElementById('id_bus').value = '{{form.bus.value}}';
            }

            setTimeout(optioncitys(), 4000)
            setTimeout(optioncitys2(), 4000)
            setTimeout(tarifas(), 4000)
            setTimeout(horario(), 4000)
      </script>
</body>

</html>

templates/ticketsHTMLS/tickets.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="{% static 'imgs/bus.ico' %}" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <title>tickets</title>
    <link rel="stylesheet" href="{% static 'css/tableTIC.css' %}">
</head>
    <body  class="body">
      
      
        <h2 class=" titulo">tus tickets</h2>
        
          <table style="width: 88%; margin-left: 7%;" class="table table-striped " >
             <thead>
              <tr>
                
                <th scope="col">imagen</th>
                <th scope="col">Nombre </th>
                <th scope="col">salida</th>
                <th scope="col">destino</th>
                <th scope="col">horario</th>
                <th scope="col">marca</th>
                <th scope="col">placa</th>
                <th scope="col">tarifa</th>
                <th scope="col-1">
                  <a class="btn btn-outline-info" href="/formrtickets"style="width: 80%; ">registar</a>
                  
                  <a class="btn btn-outline-warning" href="/graficoTickets" style="width: 80%; ">grafico</a>
                </th>
              </tr>
            </thead>
            <tbody>
              {% for ticket in tickets %}
              <tr>
                
                <td><img style="width: 70px; border-radius: 10px;" src="{% static 'imgs/ticimg.jpg' %}" alt="aca la imagen"></td>
                <td>{{ticket.nombre}}</td>
                <td>{{ticket.ciudad}}</td>
                <td>{{ticket.ciudadD}}</td>
                <td>{{ticket.hora_salida}}</td>
                <td>{{ticket.marca}}</td>
                <td>{{ticket.placa}}</td>
                <td>{{ticket.precios}}</td>
                <td>
                  
                  <a  class="btn btn-success btn" href="editarticket/{{ ticket.id }}" style="width: 80%; ">editar</a>

                  <a onclick="return confirm('esta seguro que desea borrar el ticket del usuario {{ticket.nombre}}');"  style="width: 80%; " class="btn btn-danger btn" href="borrarticket/{{ ticket.id }}"> borrar</a>  
                  </td>
              </tr>
             {% endfor %}
             
            </tbody>
          </table>
          <a class="btn btn-outline-warning" href="/menu" style="width: 8%; margin-left: 4%;">atras</a>
          <!-- <div class="card" style="width: 18rem;">
            {% for ticket in tickets %}
            <img src="{% static 'imgs/ticimg.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{ticket.ciudad}}</h5>
              <p class="card-text">{{ticket.ciudadD}}</p>
              <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
            {% endfor %}
          </div> -->
      
        <script
           src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
        </script>
  
  
  </body>
</html>